# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import blink_detection_pb2 as blink__detection__pb2


class BlinkDetectionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetEAR = channel.unary_unary(
                '/blink_detection.BlinkDetection/GetEAR',
                request_serializer=blink__detection__pb2.GetEARRequest.SerializeToString,
                response_deserializer=blink__detection__pb2.GetEARResponse.FromString,
                )


class BlinkDetectionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetEAR(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BlinkDetectionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetEAR': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEAR,
                    request_deserializer=blink__detection__pb2.GetEARRequest.FromString,
                    response_serializer=blink__detection__pb2.GetEARResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'blink_detection.BlinkDetection', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BlinkDetection(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetEAR(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/blink_detection.BlinkDetection/GetEAR',
            blink__detection__pb2.GetEARRequest.SerializeToString,
            blink__detection__pb2.GetEARResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
