"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import plistlib

plist = plistlib.load(open("Info.plist", "rb"))

APP = ["main_release.py"]
DATA_FILES = ["shape_predictor_68_face_landmarks.dat", "Info.plist"]
OPTIONS = {
    "iconfile": "icon.png",
    "plist": plist,
    "packages": ["cv2", "dlib", "grpc", "rumps", "numpy"],
}
APP_NAME = "PleaseBlink!"
setup(
    app=APP,
    data_files=DATA_FILES,
    options={"py2app": OPTIONS},
    setup_requires=["py2app"],
    name=APP_NAME,
)
